[workspace]

members = [
    "xtask",
    "yru-chorus-rs-mono",
    "yru-chorus-rs-stereo",
    "yru-echo-rs-mono",
    "yru-echo-rs-stereo",
    "yru-flanger-rs-mono",
    "yru-flanger-rs-stereo",
]

